### ISSUE TITLE
wtf couldnt import nog

### ISSUE THREAD

**Issue by mgracer48** [ToontownInfinite/src#279]

**Comment by dernise** [comment]
To fix that, TTI should share the freezetool script they have

**Comment by dernise** [comment]
Reverting this commit seems to do the trick 
https://github.com/Astron/panda3d/commit/7669e793224691a6cfb36a65a7d682dfe75735f5

**Comment by dernise** [comment]
Do you guys have any documentation how to start the .pyd made?

**Comment by MiniguyBrendan** [comment]
FreezeTool.patch may be of help.

**Comment by shuyural** [comment]
point to your prepare-client.py in cmd the once there paste this in

 ppython -m prepare_client --distribution dev --build-dir build --src-dir ..
                              --server-ver infinite-REVISION --build-mfs
                              --resources-dir ../resources
                              --include NonRepeatableRandomSourceUD.py
                              --include NonRepeatableRandomSourceAI.py
                              --exclude ServiceStart.py
                              otp toontown

and that will prepare the client
how ever i run into the issue

Preparing the client...
Build directory = build
Writing module... otp
Writing module... toontown
Using configuration file: ../config/release\dev.prc
Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Lucifer\Desktop\testing\server\ttisource-theExperiment\src-feat
ure-the-experiment\tools\prepare_client.py", line 128, in <module>
    for filepath in args.vfs:
TypeError: 'NoneType' object is not iterable

any help here?
