### ISSUE TITLE
Source code infinite.exe

### ISSUE THREAD

**Issue by dernise** [ToontownInfinite/src#304]
Hello guys!
I'm hosting a french server since june, and the way I distribute the client code is a bit.. lame.. So I was wondering if you guys could be nice enough to distribute the source code of your infinite.exe and cipherencryption, since it's the only thing I'd like to have from you.. 
Thanks!

**Comment by ToontownLittleCat** [comment]
I think that's up for the team, most likely @xPythonic to decide. (Guessing that he made the engine for TTI. Correct me if I'm wrong.)

**Comment by dernise** [comment]
@ToontownLittleCat And that's why I'm asking here :)

**Comment by mgracer48** [comment]
I need the cipher too

**Comment by kevman95** [comment]
I do not think those two things will ever be released on this github (or anywhere else for that matter) Sorry!

**Comment by mgracer48** [comment]
Bummer

**Comment by dernise** [comment]
I just finished coding one myself, I was quite bored this afternoon, thanks anyway :)

**Comment by mgracer48** [comment]
dernise mind sharing with me?
skype is mgracer48(99)

**Comment by dernise** [comment]
Added.

**Comment by misread** [comment]
The infinite runtime will **not** be released at this time.
