### ISSUE TITLE
Start_Uber_Dog

### ISSUE THREAD

**Issue by Mazeleyezer** [ToontownInfinite/src#310]
Starting the Uber_Dog doesn't work. Error:

Base channel (DEFAULT: 1000000):
===============================
Starting Toontown Infinite UberDOG server...
ppython: C:/Panda3D-1.9.0/python/ppython.exe
Base channel: 1000000
Max channels: 999999
State Server: 4002
Astron IP: 127.0.0.1:7100
Event Logger IP: 127.0.0.1:7198
===============================
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
DCFile::read of astron/dclass/otp.dc
DCFile::read of astron/dclass/toon.dc
Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\TA-418\Documents\TT\src-master\toontown\uberdog\ServiceStart.py
", line 41, in <module>
    config.GetInt('air-stateserver', 4002))
  File "toontown\uberdog\ToontownUberRepository.py", line 20, in __init__
    ToontownInternalRepository.__init__(self, baseChannel, serverId, dcSuffix='U
D')
  File "toontown\distributed\ToontownInternalRepository.py", line 14, in __init_
_
    self.netMessenger.register(0, 'shardStatus')
AttributeError: 'ToontownUberRepository' object has no attribute 'netMessenger'
Press any key to continue . . .

Note that I am using the latest /src as of today

**Comment by Mazeleyezer** [comment]
On a side note. I am interested in joining the team. I know the game is closed.

**Comment by kevman95** [comment]
You do not have the proper Panda installation with net messenger. Its not supplied on this Github, but should be somewhere if you look hard enough. or you can make your own Panda 1.9.0 with Net messenger.

Also, There is no team anymore. the game is disbanded.

**Comment by Mazeleyezer** [comment]
Ok Thanks.

**Comment by Mazeleyezer** [comment]
i Have the net messenger python files. where would i put that?

**Comment by misread** [comment]
so this is what vibrated my crotch throughout the day. closing.
