### ISSUE TITLE
Bug: Cycle

### ISSUE THREAD

**Issue by NerdyNA** [ToontownInfinite/src#311]
My uberdog server and AI server both cycle through, repeatedly saying 'ImportError: no module named semidbm', when I clearly installed semidbm. Any ideas?

**Comment by chandler14362** [comment]
Download and install semidbm. You can find it here: https://github.com/jamesls/semidbm

**Comment by NerdyNA** [comment]
As I stated in the post... 'I clearly installed semidbm'.

Meaning I installed semidbm already, and it is still saying I have errors.

**Comment by misread** [comment]
Make sure you've installed it to the Panda3D copy of Python, and not a regular version of Python.
