### ISSUE TITLE
Can't connect to account server

### ISSUE THREAD

**Issue by xJollibee** [ToontownInfinite/src#322]
When trying to login to the game, the launcher says "Can't connect to account server." Can someone please help me? I'd like to play. Thanks.

**Comment by judge2020** [comment]
@xJollibee did you just lose all your brain cells m8?

**Comment by forkrave** [comment]
lol

**Comment by xJollibee** [comment]
@judge2020 What are you talking about? m8 I just want to hop onto my 120 laff toon and play Infinite :( Why do you have to kill my vibe?

**Comment by judge2020** [comment]
@xJollibee Ok i'll kidnap @kevman95 until he turns the servers back on

**Comment by xJollibee** [comment]
THanks @judge2020 My childhood is Toontown Infinite.

**Comment by mgracer48** [comment]
lol this must be a troll

**Comment by MiniguyBrendan** [comment]
no, really?

**Comment by misread** [comment]
.
