### ISSUE TITLE
TTI opening again?!?!

### ISSUE THREAD

**Issue by judge2020** [ToontownInfinite/src#327]
https://m.facebook.com/ToontownInfinite/posts/716022775179111
Like what

**Comment by CrazyClyde** [comment]
Yes, I'd definitely classify this as an issue.

**Comment by ToontownLittleCat** [comment]
Yep, it's indeed coming back.
https://www.facebook.com/photo.php?fbid=716076721840383

**Comment by judge2020** [comment]
Since it's coming back, will the git stay public?

**Comment by ToontownLittleCat** [comment]
I hope so.

**Comment by judge2020** [comment]
What will this mean for ttf? Most people there will go back to tti, will their toons be transferred?
