### ISSUE TITLE
Hello! :O

### ISSUE THREAD

**Issue by daviddave** [ToontownInfinite/src#336]
Hi. How do you build the launcher i get no bz2lib.h error

**Comment by judge2020** [comment]
@daviddave by being a toontown h4x3r

**Comment by kevman95** [comment]
You build the launcher by NOT building it. :)

**Comment by daviddave** [comment]
where do i get bz2lib.h

**Comment by judge2020** [comment]
@daviddave go to https://akk.li/pics/anne.jpg and look for the download

**Comment by daviddave** [comment]
ha ha

**Comment by daviddave** [comment]
@kevman95 can you help?

**Comment by kevman95** [comment]
I think i already answered you.

**Comment by daviddave** [comment]
anyway are you ok??

**Comment by Loudrob** [comment]
@kevman95 hi Xemnas

**Comment by CrazyClyde** [comment]
1st. Which Panda3D version are you using?

2nd. It's a C++ header file. (bz2lib.h) You could probably look it up online. You might have to build Panda3D with it in a  certain directory to have it work.

**Comment by ToontownLittleCat** [comment]
@CrazyClyde The launcher isn't built on Panda.

**Comment by CrazyClyde** [comment]
Oh yeah. Then what compiler for C++ are you using? You could probably just include the header along with your project file if you're using Visual Studio, @daviddave

**Comment by gabrielfraser223** [comment]
I got it to successfully compile. I just downloaded bzip2 and then hardcoded them in.

**Comment by chandler14362** [comment]
For those who want to build the Windows launcher: download QT creator, build bzip2, open the launcher-win32 QT project file included in the repo.
