### ISSUE TITLE
"direct" directory missing from repository?

### ISSUE THREAD

**Issue by shawnanastasio** [ToontownInfinite/src#339]
When attempting to run the source code for the server, I've noticed that the files reference a module named "direct" which is essential to many parts of the code. Without access to the module, the server does not run at all. Are there plans to add this to the source tree or am I missing something?

Thanks,
Shawn

**Comment by encryptable** [comment]
..

**Comment by Kevman95** [comment]
....No.

**Comment by shawnanastasio** [comment]
Wow I'm smart. Thanks.
