### ISSUE TITLE
Panda3D version

### ISSUE THREAD

**Issue by shawnanastasio** [ToontownInfinite/src#340]
When running the server against the latest version of Astron's Panda3D fork, the server fails, citing an inability to import a number of deprecated modules. Is there a specific revision of Panda3D that this source needs to be used with?

**Comment by chandler14362** [comment]
Are you using Windows? If you are, I should be able to give you a link to an installer in a couple hours from now. 

Panda3D recently removed a lot of features Toontown Infinite depended on. To get those features you need to build panda3d before https://github.com/panda3d/panda3d/commit/88dbb31daa02779405ef5326677eefb5cf93f3c8 was pushed.

**Comment by shawnanastasio** [comment]
Yes I'm on windows, a link to an installer would be great, thanks.

**Comment by chandler14362** [comment]
Alright, Ill get you a link once I get home from work (~3 hours). Do you want a 32bit or 64bit build?

**Comment by shawnanastasio** [comment]
A 32-bit build would be nice, thanks.

**Comment by chandler14362** [comment]
My computer is giving me troubles building a 32bit version of the Astron panda3d fork. Maybe you could try? Here is the commit you should build from: https://github.com/Astron/panda3d/commit/b71973177bb308c1e5fe4f92951c55275ea35e50

**Comment by ToontownLittleCat** [comment]
I have just built Panda3d from Astron/panda3d@caa7cf67c797246ddecda37d9730f9f13d60c486 and it works with TTI. I can upload the installer and post it here if you like.

**Comment by shawnanastasio** [comment]
@chandler14362 That commit was one of the ones that I tried, but TTI failed to run, citing a missing module 'AstronInternalRepository'

@ToontownLittleCat I'm currently compiling the commit you suggested. If you could upload your copy in case mine fails, that would be great.

**Comment by ToontownLittleCat** [comment]
@shawnanastasio Here you go. https://www.dropbox.com/s/55let6qmy00t6g7/Panda3D-1.9.0.exe?dl=0

**Comment by chandler14362** [comment]
@ToontownLittleCat Thank you for linking the installer. I'm going to lock the issue. @shawnanastasio if you encounter any other issues, feel free to bring them to my attention.
