### ISSUE TITLE
Revert back to the original Cattlelog.

### ISSUE THREAD

**Issue by Markgasus** [ToontownInfinite/src#342]
Since our new Cattlelog was implemented poorly in the past, we'll have to revert it.

**Comment by DenialMC** [comment]
you meant Toontown-Infinite/src

**Comment by Markgasus** [comment]
Yes. Yes I did. Thank goodness I didn't make an issue here on something more confidential -- Phew!

**Comment by DenialMC** [comment]
Good thing it wasn't

Issue: Release test server tomorrow.

**Comment by CrazyClyde** [comment]
( ͡° ͜ʖ ͡°)
