### ISSUE TITLE
automatic bug reporter

### ISSUE THREAD

**Issue by mgracer48** [ToontownInfinite/src#357]
i recommend this
https://airbrake.io/

**Comment by brandonberney** [comment]
please stop

**Comment by mgracer48** [comment]
@brandonberney what did i do?
im just suggesting things for you guys :(

**Comment by brandonberney** [comment]
we already have systems in place that record crashes

**Comment by mgracer48** [comment]
I didn't know sorry.

**Comment by mgracer48** [comment]
@brandonberney please do not hate me for not knowing u made an automatic crash reporter
